# Which backend to use
LIBDNN_BACKEND ?= base

# The maximum allowable tile size, used for tile and lea backends
LIBDNN_TILE_SIZE ?= 5

# The word size for data, changes how sparse blas functions operate
LIBDNN_BITWIDTH ?= 16

# Removes/adds in loops that wait for device to die
LIBDNN_INTERMITTENT ?=

# Prints out helpful debugging information when defined
LIBDNN_CONSOLE ?=